<<<<<<< HEAD
stages:
  - deploy

deploy-to-server:
  stage: deploy
  only:
    - ae1-3/feature/schedule_recommend
  script:
    - echo 'hello world!'
  tags:
    - lsh-local
=======
image: docker:latest
services:
  - docker:dind 

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: waplmath-sap-backend:latest
  CONTAINER_NAME: waplmath-sap

stages:
  - build
  - package
  - deploy

gradle-build:
  image: java:8-jdk
  stage: build
  only:
    - ae1-3/dev
    - ae1-3/feature/schedule_recommend
  before_script: 
  script: 
    - cd WaplMath
    - ./gradlew build
  artifacts:
    paths:
      - WaplMath/build/libs/*.jar
  tags:
    - lsh-local


docker-build:
  stage: package
  only:
    - ae1-3/dev
    - ae1-3/feature/schedule_recommend
  script:
    - docker container rm -f $CONTAINER_NAME
    - docker rmi $IMAGE_NAME
    - docker build -t $IMAGE_NAME .
    - docker image ls
  tags:
    - lsh-local

docker-run:
  stage: deploy
  only:
    - ae1-3/dev
    - ae1-3/feature/schedule_recommend
  script:
    - docker run -d -p 8080:8080 --name $CONTAINER_NAME $IMAGE_NAME
    - docker container ls -a
  tags:
    - lsh-local
>>>>>>> ae1-3/feature/schedule_recommend
