image: docker:latest
services:
  - docker:dind 

variables:
  SPRING_PROFILES_ACTIVE: gitlab-ci
  DOCKER_DRIVER: overlay2
  IMAGE_NAME: waplmath-sap-backend:latest
  CONTAINER_NAME: waplmath-sap
  HS_URL: hs-registry.220.90.208.8.nip.io:443

stages:
  - build
  - package
  - deploy

gradle-build:
  image: java:8-jdk
  stage: build
  only:
    - ae1-3/dev
    - ae1-3/feature/schedule_recommend
  script: 
    - cd WaplMath
    - ./gradlew build
  artifacts:
    paths:
      - WaplMath/build/libs/*.jar
  tags:
    - lsh-local

docker-build:
  stage: package
  only:
    - ae1-3/dev
    - ae1-3/feature/schedule_recommend
  script:
    - docker rm -f $CONTAINER_NAME 2>/dev/null || true
    - docker rmi $IMAGE_NAME 2>/dev/null || true
    - docker build -t $IMAGE_NAME .
    - docker image ls
  tags:
    - lsh-local

docker-run:
  stage: deploy
  only:
    - ae1-3/dev
    - ae1-3/feature/schedule_recommend
  script:
    - docker run -d -p 8080:8080 --name $CONTAINER_NAME $IMAGE_NAME
    - docker container ls -a
  tags:
    - lsh-local