#!/usr/bin/env python3
import os
import re
import sys
import semver
import subprocess


def git(*args):
    # print(["git"] + list(args))
    return subprocess.check_output(["git"] + list(args))


def tag_repo(tag):
    url = os.environ["CI_REPOSITORY_URL"]
    # print(url)
    # url = "http://gitlab-ci-token:[MASKED]@gitlab.tmax-work.shop/waplmath/waplmath-sap-backend.git"

    # Transforms the repository URL to the SSH URL
    # Example input: https://gitlab-ci-token:xxxxxxxxxxxxxxxxxxxx@gitlab.com/threedotslabs/ci-examples.git
    # Example output: git@gitlab.com:threedotslabs/ci-examples.git
    push_url = re.sub(r'.+@([^/]+)', r'ssh://git@\1:12224', url)
    # print(push_url)
    
    git("remote", "set-url", "--push", "origin", push_url)
    git("tag", tag)
    git("push", "origin", tag)

def bump(latest):
    # TODO decide what to bump
    # Then use bump_patch, bump_minor or bump_major
    last_commit = git("log", "--oneline", "-1").decode().strip()
    if "#major" in last_commit:
        return semver.bump_major(latest)
    elif "#minor" in last_commit:
        return semver.bump_minor(latest)
    else:
        return semver.bump_patch(latest)

def main():
    try:
        latest = git("describe", "--tags").decode().strip().replace("v", "")
    except subprocess.CalledProcessError:
        # No tags in the repository
        version = "1.0.0"
    else:
        # Skip already tagged commits
        if '-' not in latest:
            print(latest)
            return 0

        version = bump(latest)

    tag_repo("v" + version)
    print("v" + version)

    return 0


if __name__ == "__main__":
    sys.exit(main())
